import Head from 'next/head'
import Script from 'next/script'

export default function Home() {
  return (
      <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src='/sc.js'></Script>
      <main>
        
      </main>
      </>
  )
}
